---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
```{r}
library(MASS)
library(ggplot2)
library(plot3D)
library(scatterplot3d)
```

```{r}
# Übergangsfunktion für den diskreten Zeitsschritt
LPA <- function(x_0, n, b, c_ea, c_pa, m_a, m_l) {
  for (i in seq_len(n)) {
    x <- x_0
    A <- matrix(c(0, 0, b*exp(-c_ea * x[3]),
                  1 - m_l, 0, 0,
                  0, exp(-c_pa * x[3]), 1 - m_a),
                nrow = 3,
                byrow = TRUE)
    x <- A %*% x
    return(x)
  }
}
```

```{r}
# Anzahl der diskreten Werte von m_a
m <- 50
# Anzahl der Iterationen
n <- 1000
# Anzahl der Punkte pro Iteration
N <- 100

# Erstes Szenario mit b = 35 --------------------
# Parameter des Modells
b <- 35
m_l <- 0.5
c_pa <- 0.09
c_ea <- 0.01
m_a <- seq(0, 1, by = 1/m)

x_s <- vector(mode = "numeric", length = m + 1) 
y <- vector(mode = "numeric", length = m + 1)

for (i in seq_along(m_a)) {
  # Fixpunkt fuer c_el = 0
  A_s <- log((1 - m_l) * b / m_a[i]) / (c_ea + c_pa)
  L_s <- A_s*b*exp(-c_ea*A_s)
  P_s <- L_s*(1 - m_l)
  x_s[i] <- L_s + P_s + A_s
  
  x_0 <- runif(3, min = 0, max = 500)
  model <- LPA(x_0, n, b, c_ea, c_pa, m_a[i], m_l)
  y[i] <- sum(model)
}

ggplot(data = data.frame(m_a = m_a, x_s = x_s, y = y)) +
  geom_point(aes(x = m_a, y = y)) +
  geom_path(aes(x = m_a, y = x_s), color = "red")

# Zweites Szenario mit b = 20 --------------------
# Parameter des Modells
b <- 20
m_l <- 0.5
c_pa <- 0.09
c_ea <- 0.01
m_a <- seq(0, 1, by = 1/m)

x_s <- vector(mode = "numeric", length = m + 1) 
y <- vector(mode = "numeric", length = m + 1)

for (i in seq_along(m_a)) {
  # Fixpunkt fuer c_el = 0
  A_s <- log((1 - m_l) * b / m_a[i]) / (c_ea + c_pa)
  L_s <- A_s*b*exp(-c_ea*A_s)
  P_s <- L_s*(1 - m_l)
  x_s[i] <- L_s + P_s + A_s
  
  x_0 <- runif(3, min = 0, max = 500)
  model <- LPA(x_0, n, b, c_ea, c_pa, m_a[i], m_l)
  y[i] <- sum(model)
}

ggplot(data = data.frame(m_a = m_a, x_s = x_s, y = y)) +
  geom_point(aes(x = m_a, y = y)) +
  geom_path(aes(x = m_a, y = x_s), color = "red")

# Chaotisches Verhalten -------------------------
m <- 1000

b <- 10.45
m_l <- 0.2
m_a <- 0.96
c_el <- 0.01731
c_pa <- 0.35
c_ea <- 0.0131

x_0 <- runif(3, min = 0, max = 500)
x <- x_0
model_chaos <- data.frame(L = c(x_0[1], rep(0, 2*(m - 1))), P = c(x_0[2], rep(0, 2*(m - 1))), A = c(x_0[3], rep(0, 2*(m - 1))))

for (i in seq_len(2*(m - 1))) {
  if ( i == m) {
    # zweiter Startwert mit minimaler Abweichung
    x <- x_0 + 0.5
  }
  x <- LPA(x, 1, b, c_ea, c_pa, m_a, m_l)
  model_chaos$L[i + 1] <- x[1]
  model_chaos$P[i + 1] <- x[2]
  model_chaos$A[i + 1] <- x[3]
}


scatterplot3d(x = model_chaos$L, y = model_chaos$P, z = model_chaos$A, color = "red", angle = 75,
  type = "p", main = "Chaotisches Verhalten", xlab = "L", ylab = "P", zlab = "A")
```

